issues/urls.py
from __future__ import absolute_import, unicode_literals
from rest_framework.routers import DefaultRouter

from .views import *

router = DefaultRouter()
router.register(r'issue', IssueViewSet)

urlpatterns = router.urls

issues/models.py
from django.db import models
from django_extensions.db.fields import (
    CreationDateTimeField, ModificationDateTimeField,
)
from django.utils.translation import ugettext_lazy as _

# Third party apps import
from tinymce.models import HTMLField
import uuid

# Local app imports ----------------

from .utils import send_mail_data
from django.conf import settings

USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class IssuesManager(models.Manager):
    def get_queryset(self):
        qs = super(IssuesManager, self).get_queryset()
        return qs.order_by('-created')  # order the queryset

    def issue_list_by_status(self, status):
        issues = Issues.objects.filter(status=status)
        return issues

    def issue_list_by_priority(self, priority):
        issues = Issues.objects.filter(priority=priority)
        return issues

    def issue_list_by_classification(self, classification):
        issues = Issues.objects.filter(classification=classification)
        return issues

    def issue_list_by_status_and_owner(self, status, user):
        issues = Issues.objects.filter(status=status, issue_owner=user)
        return issues


    def issue_list_by_priority_and_owner(self, priority, user):
        issues = Issues.objects.filter(priority=priority, issue_owner=user)
        return issues

    def issue_list_by_classification_and_owner(self, classification, user):
        issues = Issues.objects.filter(classification=classification, issue_owner=user)
        return issues

    def delete_by_status(self, status):
        Issues.objects.filter(status=status).delete()
        return True


def get_attachment_file_path(instance, filename):
    """
    Produces a unique file path for the upload_to of a FileField.

        The produced path is of the form:
        "[model name]/[field name]/[random name].[filename extension]".
    """

    new_filename = "%s.%s" % (uuid.uuid4(),
                              filename.split('.')[-1])
    return '/'.join([instance.__class__.__name__.lower(),
                    new_filename])


class TimeStampedModel(models.Model):
    """ TimeStampedModel
    An abstract base class model that provides self-managed "created" and
    "modified" fields.
    """
    created = CreationDateTimeField(_('created'))
    modified = ModificationDateTimeField(_('modified'))

    class Meta:
        get_latest_by = 'modified'
        ordering = ('-modified', '-created',)
        abstract = True


# Creat unique issue number
def increment_issue_number():
    try:
        issues = Issues.objects.order_by('-pk')[0]
        if not issues:
            return '#0001'
        issue_no = issues.issue_no
        issue_int = int(issue_no.split('#')[-1])
        width = 4
        new_issue_int = issue_int + 1
        formatted = (width - len(str(new_issue_int))) * "0" + str(new_issue_int)
        new_issue_no = '#' + str(formatted)
        return new_issue_no
    except:
        new_issue_no = '#0001'
        return new_issue_no


STATUS_CHOICES = [
    ('Open', 'Open'),
    ('On-hold', 'On-hold'),
    ('Escalated', 'Escalated'),
    ('Closed', 'Closed')
]

PRIORITY_CHOICES = [
    ('None', 'None'),
    ('High', 'High'),
    ('Medium', 'Medium'),
    ('Low', 'Low')
]

CLASSIFICATION_CHOICES = [
    ('Query', 'Query'),
    ('Issue', 'Issue'),
    ('Feature', 'Feature'),
    ('Suggestion', 'Suggestion'),
    ('Improvement', 'Improvement'),
    ('Other', 'Other')
]

USER_TYPE = (
    ('EMPLOYEE', 'Employee'),
    ('CONSULTANT', 'Consultant'),
    ('OWNER', 'Owner'),
    ('WRONG', 'Wrong'))


class Issues(TimeStampedModel):
    issue_owner = models.ForeignKey(USER_MODEL, related_name='issue_owner')
    issue_no = models.CharField(max_length = 500, null = True, blank = True)
    title = models.CharField(max_length=200, blank=True, null=True)
    owner_phone_number = models.CharField(max_length=25,blank=True, null=True)
    assigned_to_user = models.ForeignKey(USER_MODEL, null=True, blank=True, related_name='assigned_to_user')
    description = HTMLField(null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=255, default='Open')
    issue_priority = models.CharField(choices=PRIORITY_CHOICES, max_length=255, default='None')
    classification = models.CharField(choices=CLASSIFICATION_CHOICES, max_length=255, null=True, blank=True)
    owner_role = models.CharField(choices=USER_TYPE, max_length=255, null=True, blank=True)
    snapshot = models.FileField(upload_to=get_attachment_file_path, max_length=500, null=True,blank=True, verbose_name="snapshot")
    due_date = models.DateTimeField(null=True, blank=True)
    objects = IssuesManager()

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.issue_no:
            self.issue_no = increment_issue_number()
        if self.pk is not None:
            orig = Issues.objects.get(pk=self.pk)
            link = "http://" + settings.DOMAIN_URL + "/issues/" + str(self.id)
            if not orig.assigned_to_user and self.assigned_to_user:
                context = {"type":"Issue_Assigned", "template":"IssueAssigned", "link":link, "issue_no": self.issue_no, "issue_title":self.title, "descrption":self.description, "created_by":self.issue_owner.username, "priority":self.issue_priority, "classification":self.classification, "assigned_to":self.assigned_to_user.username, "email_to":self.assigned_to_user.email, "created_at":self.created}
                send_mail_data(context)
            elif orig.assigned_to_user:
                    if orig.assigned_to_user != self.assigned_to_user:
                        context = {"type":"Issue_Assigned", "template":"IssueAssigned", "link":link, "issue_no": self.issue_no, "issue_title":self.title, "descrption":self.description, "created_by":self.issue_owner.username, "priority":self.issue_priority, "classification":self.classification, "assigned_to":self.assigned_to_user.username, "email_to":self.assigned_to_user.email, "created_at":self.created}
                        send_mail_data(context)
        super(Issues, self).save(*args, **kwargs)

issues/templates/issues/issue-base.html
{% load bootstrap %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <title>ckiller</title>
    <meta name="description" content="">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=RobotoDraft:100,100italic,300,300italic,400,500,700,900,400italic">
    <!-- Place favicon.png in the root directory -->
    <link rel="icon" type="image/png" href="favicon.png" />
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">#}
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/datepicker.css">#}
{#    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">#}

     <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->


{#    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.js"></script>#}
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/npm.js"></script>#}

    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.formset.js"></script>
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>#}
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>#}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.validate.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>


    <style>
        body
        {
            font-family: RobotoDraft, Roboto, 'Helvetica Neue', sans-serif;
        }

        p {
          font-size: 1.1rem;
          font-weight: 400;
          letter-spacing: 0.010em;
          margin: 1.6rem 0;
        }

        .status-data {
    border-radius: 6px;
    color: #fff;
    display: inline-block;
    font-size: 85%;
    min-width: 54px;
    padding: 1px 10px;
    text-align: center;
    -webkit-align-content: center;
    -ms-flex-line-pack: center;
    align-content: center;
    margin-top: -0.5%;
    float: right;
}

        .margin-right-10 {
    margin-right: 10px !important;
}
        .status-invoice, .status-paid {
    background-color: #8bc34a;
}

        .status-timesheet-rejected, .status-invoice-rejected {
    background-color: #ff5722;
}

        .status-new {
    background-color: #00BCD4;
}


    </style>


</head>
<body>
<div class="container-fluid">

    <nav>
    <div class="nav-wrapper" style="background-color: #FC91AD!important;">
      <a href="#" allign="center" class="brand-logo"><img width="250px" src="/media/logo.png"></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
            <li><a><strong>Hello {{ user.username }}</strong></a></li>
            <li><a href="/api/issue-list/">Issues</a></li>
          <li><a href="/api/accounts/logout/">Logout</a></li>
          {% else %}
            <li><a href="/api/accounts/login/">Login</a></li>
          {% endif %}
      </ul>
    </div>
  </nav>

{% block content %}

{% endblock %}
</div>
</body>
</html>

issues/templates/issues/issue-details.html
{% extends "issues/issue-base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-zero{% endblock %}

{% block body_class %}home{% endblock %}

{% block content %}
{#    <nav class="nav-wrapper" >#}
{#        <h2 align="center">{{ issue.issue_no }}</h2>#}
{#    </nav>#}


    <div class="row">

    <div class="alert alert-info" id="successMessage" role="alert" style="display: none;">Status for issue is updated</div>

        <div class="col s8 card">
        <div class="card-content">
            <div class="row ">

                    <h4 class="colr ng-binding" align="center" style="color: #07a;">{{ issue.issue_no }}</h4>

            </div>
        <div class="row">
                <div class="col s12">
                    <p><strong>Title : </strong>{{ issue.title }}</p>
                </div>
        </div>
            <div class="row">

                <div class="col s6">
                    <p><strong>Created at : </strong>{{ issue.created }}</p>
                </div>

                <div class="col s6">
                    <p><strong>Created by : </strong>{{ issue.issue_owner.username }}</p>
                </div>

            </div>

        <div class="row">
                <div class="col s6">
                    <p><strong>Email : </strong>{{ issue.issue_owner.email }}</p>
                </div>

                <div class="col s6">
                    <p><strong>Contact Number : </strong>{{ issue.owner_phone_number }}</p>
                </div>

            </div>

            <div class="row">


            <div class="col s6">
                    <p><strong>Priority :</strong> {{ issue.issue_priority }}</p>
                </div>

            <div class="col s6">
                    <p><strong>Classification :</strong> {{ issue.classification }}</p>
                </div>

            </div>
            <div class="row">

            <div class="input-field col s6">
        {% if group in request.user.groups.all %}


{#            {% if user.groups__name == "Tickets" %}#}
                <p><strong>Assigned To :</strong>
                        {% if issue.assigned_to_user.username %}{{ issue.assigned_to_user.username }}{% else %}
                            None {% endif %}</p>
                {% else %}
                <select class="assignedto" id="id_assignedto" name="assignedto">
                            {% for userr in users %}
                                <option value="{{ userr.id }}" {% if issue.assigned_to_user == userr %} selected {% endif %}>{{ userr.username }}</option>
                            {% endfor %}
                        </select>
                            <label>Assigned To</label>

            {% endif %}

                </div>


                <div class="col s6">
                        <div class="input-field col s12">


                            <select class="statusnew" id="id_status" name="status">
                            {% for stat in statuses %}
                                <option value="{{ stat }}" {% if issue.status == stat %} selected {% endif %}>{{ stat }}</option>
                            {% endfor %}
                        </select>
                            <label>Status</label>
                            <input id="issue_iddata" type="hidden" value="{{ issue.id }}">


                        </div>

                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <strong>Description:</strong>

                    <div style="margin-left: 2%;">{{ issue.description|safe }}</div>
                </div>
            </div>
            <div class="row">
                <div class="col s10">
                    <strong>Attachment</strong>

                    <img class="materialboxed" width="600" src="/media/{{ issue.snapshot }}" />
                </div>
            </div>
        </div>
        </div>
        <div class="col s4" style="border-left: groove #000000; margin-top: 2%;">
            <div class="row">
                <h5 style="margin-left: 4%;margin-bottom:4%;color: #07a;">Comments</h5>

                <div class=" col s10 ">
                    <input placeholder="Add comment" type="text" class="validate" id="comment" style="height: 100%;"/>
                </div>
                <div class="col s2">
                    <a class="btn-floating btn-small waves-effect waves-light light-blue tooltipped" data-position="bottom" data-delay="50" data-tooltip="Add comment" value="Comment" id="id_comment"><i class="material-icons">+</i></a><input type="hidden" value="{{ issue.id }}">
                </div>
            </div>

            <div class="row" style="margin-left: 2%;">
                <ul ng-if="showCommentList" ng-repeat="comment in commentList" class="mini-timeline ng-scope">
                    {% for comment in comments %}
                        <li class="mini-timeline-lime card">
                            <div class="timeline-icon"></div>
                            <div class="timeline-body" style="margin-left: 5%;">
                                <div class="timeline-content ng-binding">
                                    <p>{{ comment.comment }}
                                    <a href="#" class="name ng-binding"> - {% if comment.user.username == user.username %} You {% else %} {{ comment.user.username }}{% endif %}</a></p>
                                    <!--{"data":"{u'from': u'follow up', u'target': u'Radha saha', u'target_id': 57, u'target_type': u'consultant', u'actor': u'ram', u'to': u'follow up', u'verb': u' has updated status from follow up to follow up of ', u'actor_type': u'user', u'actor_id': 2, u'action_object': u'', u'operation': u'status', u'type': u'update'}","verb":"has updated status from follow up to follow up of","action_object_id":"None","actor_id":"2","action_object":"None","timestamp":"2 weeks, 5 days","target_id":"57","actor":"ram","target":"Radha saha","route":"/timeline/activity","reqParams":null,"restangularized":true,"fromServer":true,"parentResource":null,"restangularCollection":false} 2 weeks, 5 days ago-->
                                    <span class="time ng-binding" style="margin-left: 5%;">On {{ comment.submit_date }}</span>
                                </div>
                            </div>
                        </li><br/>
                        </ul>
                    {% endfor %}
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {

            $('select').material_select();

            $('#id_status').on('change', function () {
                var stat = $(this).find('option:selected').val();
                var obj_id = $('#issue_iddata').val();
                var data = {
                    status: stat,
                    object_id: obj_id
                };

                $.ajax({
                    url: "/api/update-issue-status/",
                    type: "POST",
                    data: data,
                    success: function (response) {
                                   Materialize.toast('Status updated', 4000);
                    },
                    error: function () {

                    }
                });
            });


            $('#id_assignedto').on('change', function () {
                var stat = $(this).find('option:selected').val();
                var obj_id = $('#issue_iddata').val();
                var data = {
                    status: stat,
                    object_id: obj_id
                };

                $.ajax({
                    url: "/api/update-assigned-to/",
                    type: "POST",
                    data: data,
                    success: function (response) {
                                   Materialize.toast('issue assignee changed', 4000);
                    },
                    error: function () {

                    }
                });
            });




            $('#id_comment').on('click', function () {
                var comment = $('#comment').val();
                var obj_id = $(this).next().val();
                var data = {
                    comment: comment,
                    object_id: obj_id
                };

                $.ajax({
                    url: "/api/add-comment-data/",
                    type: "POST",
                    data: data,
                    success: function (response) {
                                Materialize.toast('Comment added successfully', 4000);
                                    location.reload();
                    },
                    error: function () {

                    }
                });
            });


        });
    </script>



{% endblock %}

issues/templates/issues/issues_list.html
{% extends "issues/issue-base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-zero{% endblock %}

{% block body_class %}home{% endblock %}

{% block content %}
        <h4 align="center">Issues List</h4>

    <div class="row">
        <div class="col s12 m12">
            {% for issue in issues %}
               <a href="/api/issue-details/{{ issue.id }}">
                <div class="card darken-1" style="height: 50px!important;">
                <div class="card-content">
                  <span class="card-title" style="line-height: 2px!important;">{{ issue.issue_no }} - {{ issue.title }}</span>
                    {% if issue.assigned_to_user %}<span class=" ng-binding" style="margin-left:50%;"> Assigned to : {{ issue.assigned_to_user.username }} </span>{% endif %}
                    <span class="status-data ng-binding status-invoice margin-right-10"> {{ issue.issue_priority }} </span>
                    <span class="status-data ng-binding status-timesheet-rejected margin-right-10"> {{ issue.classification }} </span>
                    <span class="status-data ng-binding status-new margin-right-10"> {{ issue.status }} </span>
                </div>
              </div>
            </a>
        {% endfor %}
        </div>
      </div>


{#        <ul >#}
{#             {% for issue in issues %}#}
{#                 <a href="/api/issue-details/{{ issue.id }}"><li class="card">{{ issue.issue_no }}</li></a>#}
{#            {% endfor %}#}
{#        </ul>#}
{% endblock %}